---
- name: Copy bash_history
  copy:
    src: .bash_history
    dest: /home/darlene
    mode: 0664
    owner: darlene
    group: darlene

- name: Change darlene's home permissions
  file:
    dest: /home/darlene
    mode: 0755
    owner: darlene
    group: darlene
     
- name: Copy private key for elliot
  copy:
    src: id_rsa
    dest: /home/elliot/.ssh
    mode: 0750
    owner: elliot
    group: elliot

- name: Copy Bad Shadow
  copy:
    src: /etc/shadow
    dest: /etc/shadow.backup
    mode: 0644
    owner: root
    group: root
    remote_src: True