---
galaxy_info:
  author: kulinacs
  description: Configures dhcpcd
  license: ISC
  min_ansible_version: 1.2
  platforms:
    - name: Void Linux
      versions:
        - any
  galaxy_tags:
    - dhcpcd
    - network
dependencies: []
