---
 - name: Copy private key for elliot
   copy:
     src: id_rsa
     dest: /home/elliot/.ssh
     mode: 600
     owner: elliot
     group: elliot

 - name: Copy public key for elliot
   copy:
     src: id_rsa.pub
     dest: /home/elliot.ssh
     mode: 600
     owner: elliot
     group: elliot
 - name: keypass password
   copy:
     src: Private.kdbx
     dest: /etc/security
     mode: 664
     owner: elliot
     group: elliot