---
- name: Install vsftpd
  xbps:
    pkg: vsftp
    state:: present

- name: Configure vsftpd
  template:
    copy:
      src: vsftpd.conf
      dest: /etc/
      owner: root
      group: root
      mode: 0644
  notify: ftp